/*
 * Item.js
 * Schema Generated by RikkiTikki
 * Add custom Schema Validators, Types and Methods below
 */
var API = require('rikki-tikki');

var Item = new API.Schema(
  API.extend(API.getSchemaTree('Item'),
  {
    // place custom Schema Type overrides here
  })
);

/*
 * Virtual Getters/Setters
 */
Item.virtuals = {
  
};

/*
 * Static Methods
 */
Item.statics = {
  
};

/*
 * Custom Schema Validators
 */
Item.validators = {
  
};

module.exports = API.model('Item', Item);